Models/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models.Models
{
    public class CategoryViewModel
    {
        public int CategoryId { get; set; }
        [Display(Name ="Kategori Adi")]
        public string CategoryName { get; set; }

        [Display(Name ="Stok sayisi")]
        public int Stock { get; set; }
    }
}

Models/Models/ProductInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Models.Models
{
    public class ProductInfoViewModel
    {
        public string ProductName { get; set; }
        public DateTime OrderDate { get; set; }
    }

    public class ProductViewModel
    {
        public string ProductName { get; set; }
    }
}

Models/Models/StudentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models.Models
{
    public class StudentViewModel
    {
        public int StudentId { get; set; }

       
        [Required(ErrorMessage ="Lutfen Ogrenci adi giriniz!")]
        [Display(Name ="Ögrenci Adı")]
        [MinLength(3,ErrorMessage ="En az 3 karakter girin")]
        [MaxLength(6,ErrorMessage ="En fazla 6 karakter girebilirsiniz")]
        public string StudentName { get; set; }
        //public bool IsPass { get; set; }

        [Required(ErrorMessage = "Ortalama deger girin")]
        [Display(Name = "Ortalama")]
        public int Avarage { get; set; }


        [Required(ErrorMessage = "e-posta girin")]
        [Display(Name = "e-posta")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required(ErrorMessage = "e-posta tekrar girin")]
        [Display(Name = "e-posta")]
        [Compare("Email",ErrorMessage ="eposta adresleri aynı değil")]
        [DataType(DataType.EmailAddress)]
        public string Email2 { get; set; }

        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Date)]
        public DateTime BirthDay { get; set; }

    }
}

Models/Models/TeacherViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Models.Models
{
    public class TeacherViewModel
    {
        public int TeacherId { get; set; }

        [Display(Name = "Ögretmen Adı")]
        [MinLength(3, ErrorMessage = "En az 3 karakter girin")]
        [MaxLength(6, ErrorMessage = "En fazla 6 karakter girebilirsiniz")]
        public string TeacherName { get; set; }

        [Display(Name = "e-posta")]
        [DataType(DataType.EmailAddress,ErrorMessage ="eposta yanlış")]
        public string Email { get; set; }

   
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [DataType(DataType.Date)]
        public DateTime BirthDay { get; set; }
    }
}

Models/Controllers/AttributesController.cs
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class AttributesController : Controller
    {
        // GET: Attributes
        public ActionResult ServerSideValidation(StudentViewModel rd)
        {
            //ModelState.IsValid
            //Post gelen model nesnesinde ki propertylere verilen degerde herhangi bir eksiklik varsa ve egerki propertylere attribute ile kuralları sağlamıyorsa, ModelState.IsValid ozelligi false olur.
            //False oldugu zamanda validation calistirilir. View deki
            //Html.ValidationSummary()

            //ActionMetod argumani model tipinde olmalıdır ModelState kontrol edilebilmesi için.
            /*Validasyon (ModelState durumu)Modellerden Required attribute almayan string harici 
            tüm veri tipleri için geçerlidir.
            
             */

            if (!ModelState.IsValid)
            {

            }
            return View();
        }

        public ActionResult ClientSideValidationJquery()
        {
            return View();
        }
    }
}

Models/Controllers/BindAttributeController.cs
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class BindAttributeController : Controller
    {
        // GET: BindAttribute
        public ActionResult Index()
        {
            return View(new CategoryViewModel() { CategoryId=1,CategoryName="Temizlik Urunleri",Stock=100});
        }

        public ActionResult ExcludePost(CategoryViewModel arg)
        {
            return RedirectToAction("Index");
        }
    }
}

Models/Controllers/CustomDefaultModelBinderController.cs
using Models.CustomBinders;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class CustomDefaultModelBinderController : Controller
    {
        public ActionResult Index()
        {
            return View(new ProductViewModel() { ProductName = "Laptop" });
        }

        [HttpPost]
        public ActionResult PostProductInfo([ModelBinder(typeof(ProductInfoModelDefaultBinder))] ProductInfoViewModel arg)
        {
            return View();
        }
    }
}

Models/Controllers/CustomModelBindingController.cs
using Models.CustomBinders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class CustomModelBindingController : Controller
    {
        // GET: CustomModelBinding
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetTime([ModelBinder(typeof(DateTimeModelBinder))] DateTime arg)
        {
            /*
             Action Cagrilamadan önce, arka plan işlemlerini yöneten, iki tane birleşen var.
             ValueProviderDictionary
             DefaultModelBinder.

             ValueProviderDictionary:
             HTTP request ile gelen parametreleri çekerek string halde depolar, bunu şu adımlara göre yapar.
             1-Request.Form["name"] varmi diye bakar.
             Yoksa
             RouteData.Values["name"] varmi diye bakar
             yoksa
             Request.QueryString["name"] varmi diye bakar
             yoksa
             null değer döndürü.

             DefaultModelBinder
             temel tipler için bir işlem yapmaz ancak model TEMPLATE için reflection ile propertyler ValueProviderDictionary sınıfı tarafından sağlanan değerleri alır.
              */

            return PartialView("Index", arg.ToString());
        }
    }
}

Models/Controllers/CustomProductInfoBinderController.cs
using Models.CustomBinders;
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class CustomProductInfoBinderController : Controller
    {
        // GET: CustomProductInfoBinder
        public ActionResult Index()
        {
            return View(new ProductViewModel() { ProductName = "Laptop" });
        }

        [HttpPost]
        public ActionResult PostProductInfo([ModelBinder(typeof(ProductInfoModelBinder))] ProductInfoViewModel arg)
        {
            return View();
        }
    }
}

Models/Controllers/DataTypesController.cs
using Models.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Models.Controllers
{
    public class DataTypesController : Controller
    {
        // GET: DataTypes
        public ActionResult Index(TeacherViewModel arg)
        {
            if(!ModelState.IsValid)
            {

            }

            return View();
        }
    }
}

Models/Views/Attributes/ClientSideValidationJquery.cshtml
@model Models.Models.StudentViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ClientSideValidationJquery</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            @*@Html.ValidationSummary()*@

            @Html.LabelFor(m => m.StudentName)
            @Html.TextBoxFor(m => m.StudentName)
            @Html.ValidationMessageFor(m => m.StudentName)
            <br />

            @Html.LabelFor(m => m.Avarage)
            @Html.TextBoxFor(m => m.Avarage)
            @Html.ValidationMessageFor(m => m.Avarage)
            <br />


            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
            <br />

            @Html.LabelFor(m => m.Email2)
            @Html.TextBoxFor(m => m.Email2)
            @Html.ValidationMessageFor(m => m.Email2)
            <br />

            <input type="submit" name="gonder" value="Gönder" />
        }

    </div>
    <script src='@Url.Content("~/Scripts/jquery-1.10.2.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery.validate.min.js")' type="text/javascript"></script>
    <script src='@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")' type="text/javascript"></script>
     
</body>
</html>

Models/Views/Attributes/ServerSideValidation.cshtml
@model Models.Models.StudentViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            @*@Html.ValidationSummary()*@

            @Html.LabelFor(m => m.StudentName) 
            @Html.TextBoxFor(m => m.StudentName)
            @Html.ValidationMessageFor(m=>m.StudentName)
            <br />

            @Html.LabelFor(m => m.Avarage) 
            @Html.TextBoxFor(m => m.Avarage)
            @Html.ValidationMessageFor(m => m.Avarage)
            <br />


            @Html.LabelFor(m => m.Email)
            @Html.TextBoxFor(m => m.Email) 
            @Html.ValidationMessageFor(m => m.Email)
            <br />

            @Html.LabelFor(m => m.Email2)
            @Html.TextBoxFor(m => m.Email2) 
            @Html.ValidationMessageFor(m => m.Email2)
            <br />

            <input type="submit" name="gonder" value="Gönder"/>
        }
      
    </div>
</body>
</html>

Models/Views/BindAttribute/Index.cshtml
@model Models.Models.CategoryViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm("ExcludePost","BindAttribute",FormMethod.Post))
        {
             @Html.LabelFor(m=>m.CategoryName) 
             @Html.EditorFor(m=>m.CategoryName)
            <br />
            @Html.LabelFor(m=>m.Stock)
            @Html.EditorFor(m=>m.Stock)
            <input type="submit" value="Gonder" name="gonder"/>
        }
    </div>
</body>
</html>

Models/Views/DataTypes/Index.cshtml
@model Models.Models.TeacherViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            @*@Html.ValidationSummary()*@

            @Html.LabelFor(m => m.TeacherName)
            @Html.TextBoxFor(m => m.TeacherName)
            @Html.ValidationMessageFor(m => m.TeacherName)
            <br />


            @Html.LabelFor(m => m.Email)
            @Html.EditorFor(m => m.Email)
            @Html.ValidationMessageFor(m => m.Email)
            <br />

            @Html.LabelFor(m => m.Password)
            @Html.EditorFor(m => m.Password)
            @Html.ValidationMessageFor(m => m.Password)
            <br />

            @Html.LabelFor(m => m.BirthDay)
            @Html.EditorFor(m => m.BirthDay)
            @Html.ValidationMessageFor(m => m.BirthDay)
            <br />

            <input type="submit" name="gonder" value="Gönder" />
        }

    </div>
</body>
</html>