HtmlHelpers/Controllers/StandardHtmlHelpersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HtmlHelpers.Controllers
{
    public class StandardHtmlHelpersController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ActionLink()
        {
            return View();
        }

        public ActionResult Ekran(string Arguman)
        {
            if (!string.IsNullOrEmpty(Arguman))
                ViewBag.Deger = Arguman;
            return View();
        }

        public ActionResult BeginForm()
        {
            return View();
        }

        public ActionResult TextBox(object adi)
        {
            return View();
        }

        public ActionResult Label()
        {
            return View();
        }

        public ActionResult TextArea(string txt,string lst,FormCollection frm)
        {
            var ilkdeger = frm["txt"];
            var ikincideger = frm["lst"];
            return View();
        }

        public ActionResult CheckBox(object ch,FormCollection frm)
        {
            return View();
        }

        public ActionResult RadioButton(string radio,FormCollection frm)
        {
            return View();
        }

        public ActionResult DropDownList()
        {
            return View();
        }

        public ActionResult ListBox()
        {
            return View();
        }

        public ActionResult Password()
        {
            return View();
        }
    }
}

HtmlHelpers/Views/StandardHtmlHelpers/ActionLink.cshtml
@{
    ViewBag.Title = "ActionLink";
}
<style type="text/css">
    .benim
    {
        font-family:Verdana;
        color:red;
    }
</style>
<h2>ActionLink</h2>
@*Bu Htmlhelper Html deki a href üretir.*@
@Html.ActionLink("Gönder","Ekran")

@Html.ActionLink("Gönder2", "Ekran","Home")

<p>routeValues ile</p>
@Html.ActionLink("Gönder3", "Ekran", new { Arguman = "hello" })

<p>html attributes ile</p>
@Html.ActionLink("Gönder4", "Ekran", null,new { @class = "btn btn-primary btn-lg" })

<p>html attributes ile</p>
@Html.ActionLink("Gönder5", "Ekran", null, new { @class = "benim" })

<p>html attributes ile</p>
@Html.ActionLink("Gönder6", "Ekran", null, new { @style = "font-size:24px; font-weight:bold; color:purple;" })

HtmlHelpers/Views/StandardHtmlHelpers/BeginForm.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>BeginForm</title>
    <style>
        .bform {
            border-color: red;
            border-width: 5px;
            border-style: solid;
        }
    </style>
</head>
<body>
    <div>
        @*Html.BeginForm() html de ki form post elementinin
            karşılığıdır.*@
        @using (Html.BeginForm())
        {
            <input type="submit" name="kaydet" value="Kaydet" />
        }

    </div>
    <fieldset>
        <legend>Begin Form FormMethod argumani ile</legend>
        @using (Html.BeginForm("Ekran", "StandardHtmlHelpers", FormMethod.Post))
        {
            <button type="submit" name="btn">Kaydet2</button>
        }
    </fieldset>
    <hr />
    <fieldset>
        <legend>Begin Form style ile</legend>
        <div>
            @using (Html.BeginForm("Ekran", "Home", FormMethod.Post, new { @class = "bform" }))
            {
                <button type="submit" name="btn2">Kaydet2</button>
            }
        </div>
    </fieldset>
    <hr />
    <fieldset>
        <legend>Begin Form arguman ile</legend>
        <div>
            @using (Html.BeginForm("Ekran", "StandardHtmlHelpers", new { Arguman = "Selam" }, FormMethod.Post, new { @class = "bform" }))
            {
                <button type="submit" name="btn2">Kaydet3</button>
            }
        </div>
    </fieldset>
    <hr />
    <fieldset>
        <legend>Html input kullarak</legend>
        <div>
            @using (Html.BeginForm("Ekran", "StandardHtmlHelpers", FormMethod.Post, new { @class = "bform" }))
            {
                <div class="editor-label">
                    <label>Adı:</label>
                </div>
                <div class="editor-field">
                    <input name="adi" type="text" />
                </div>
                <div class="editor-label">
                    <label>Soyadı:</label>
                </div>
                <div class="editor-field">
                    <input name="soyadi" type="text"/>
                </div>
                <button type="submit" name="btn2">Kaydet3</button>
            }
        </div>
    </fieldset>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/CheckBox.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>CheckBox</title>
</head>
<body>
    <div> 
        <fieldset>
            <legend>
                @*Html deki input value checkbox olan html helper metodudur*@
                form actionda  hatirlama

            </legend>
            <form action="">
                <input type="checkbox" name="vehicle1" value="Bike"> I have a bike<br>
                <input type="checkbox" name="vehicle2" value="Car"> I have a car<br>
                <input type="checkbox" name="vehicle3" value="Boat" checked> I have a boat<br><br>
                <input type="submit" value="Submit">
            </form>

        </fieldset>
    </div>
    <hr/>
    <fieldset>
        <legend>
            Kullanimi
        </legend>
        Is Ok: @Html.CheckBox("chk", "Tamam")

    </fieldset>
    <fieldset>
        <legend>
            Begin Form ile, checkbox degeri belirleyebiliriz.

        </legend>

        @using (Html.BeginForm())
        {
            @Html.Label("ch","Is Ok:")
            @Html.CheckBox("ch", new { Name="Tamam"})
            <input type="submit" name="save" value="Gönder"/>
        }
    </fieldset>
    <fieldset>
        <legend>
            Begin Form ile, HtmlHelper ilgili checkbox icin hidden
            input uretir, varsayilan degeri bool dur.
        </legend>

        @using (Html.BeginForm())
        {
            @Html.Label("ch", "Is Ok:")
            @Html.CheckBox("ch")
            <input type="submit" name="save" value="Gönder" />
        }
    </fieldset>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/DropDownList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>DropDownList</title>
</head>
<body>
    <div> 
        <fieldset>
            <legend>
                Tanım:
            </legend>
            @Html.DropDownList("dropdown",
           new[]
           {
               new SelectListItem { Value="1",Text="Matematik" },
               new SelectListItem { Value="2",Text="Fizik"},
               new SelectListItem { Value="3",Text="Biyoloji" },
               new SelectListItem { Value="4",Text="Turkce",Selected=true},
           })
        </fieldset>
    </div>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/Ekran.cshtml
@{
    ViewBag.Title = "Ekran";
}

<h2>Ekran</h2>
<p>@ViewBag.Deger</p>

HtmlHelpers/Views/StandardHtmlHelpers/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

HtmlHelpers/Views/StandardHtmlHelpers/Label.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Label</title>
</head>
<body>
    <div> 
        <fieldset>
            <legend> Tanım : Html deki label elementi
            For attribute ile belirtilen deger id ile
            belirtilen html element değerini niteler. For
            genellikle checkbox ve radio gibi kontroller deki 
            click olayını tetikler.
            </legend>
            <form action="">
                <label for="male">Male</label>
                <input type="radio" name="gender" id="male" value="male"><br>
                <label for="female">Female</label>
                <input type="radio" name="gender" id="female" value="female"><br>
                <label for="other">Other</label>
                <input type="radio" name="gender" id="other" value="other"><br><br>
                <input type="submit" value="Submit">
            </form>
        </fieldset>
    </div>
    <fieldset>
        <legend>Html Helper metodu olan Html.Label karşılığı</legend>
        
        @Html.Label("male1","Male",new {@style="color:red; font-style:italic;" })
         
        <input type="radio" name="gender" id="male1" value="male"><br>
        @Html.Label("female1","Female")

        <input type="radio" name="gender" id="female1" value="female"><br> 
    </fieldset>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/ListBox.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ListBox</title>
</head>
<body>
    <fieldset>
        <legend>
            Tanım:
        </legend>
        @Html.ListBox("lstbox",
           new[]
           {
               new SelectListItem { Value="1",Text="Matematik" },
               new SelectListItem { Value="2",Text="Fizik"},
               new SelectListItem { Value="3",Text="Biyoloji" },
               new SelectListItem { Value="4",Text="Turkce",Selected=true},
           })
    </fieldset>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/Password.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Password</title>
</head>
<body>
    <div> 
        @using (Html.BeginForm())
        {
            @Html.Password("password")
            <input type="submit" name="save" value="Gonder"/>
        }
     
    </div>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/RadioButton.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>RadioButton</title>
</head>
<body>
    <div> 
        <fieldset>
            <legend>Html radio button</legend>
            <form action="">
                <input type="radio" name="gender" value="male"> Male<br>
                <input type="radio" name="gender" value="female"> Female<br>
                <input type="radio" name="gender" value="other"> Other
            </form>
        </fieldset>
    </div>
    <fieldset>
        <legend>Html helper metodu Kullanim</legend>
        @Html.Label("m","Male")
        @Html.RadioButton("radio1","male",new { id = "m" })<br />
        @Html.Label("f","Female")
        @Html.RadioButton("radio1","female",new { id="f"})<br />
        @Html.Label("o","Other")
        @Html.RadioButton("radio1","other",new { id = "o" })
    </fieldset>
    <div>
        <fieldset>
            <legend>Begin Form ile</legend>
            @using (Html.BeginForm())
            {
                @Html.Label("mm", "Male")
                @Html.RadioButton("radio", "male",true, new { id = "mm" })<br />
                @Html.Label("ff", "Female")
                @Html.RadioButton("radio", "female", new { id = "ff" })<br />
                @Html.Label("oo", "Other")
                @Html.RadioButton("radio", "other", new { id = "oo" })

                <input type="submit" name="save" value="Gönder"/>
            }
        </fieldset>
    </div>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/TextArea.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TextArea</title>
</head>
<body>
    <div> 
        @*Html de ki <textarea/> elementinin karışılığı  Html helper metodu olan Html.TextArea dır.*@
        
        <fieldset>
            <legend>Html.TextArea(string name) helper metodu ile</legend>
            Adres : @Html.TextArea("txtAddress")<br />
            
        </fieldset>
    </div>

    <hr />
    <fieldset>
        <legend>Html.BeginForm ile:</legend>
        @using (Html.BeginForm())
        {
            @Html.TextArea("txt")<br />
            @Html.TextArea("txt")

            <input type="submit" name="save" value="Kaydet"/>
        }
    </fieldset>
    <fieldset>
        <legend>Varsayilan deger ile:</legend>
        @using (Html.BeginForm())
        {
            @Html.TextArea("txt","Balat mahallesi bitisikbaglar sokak")<br />
            @Html.TextArea("lst","Varsayilan deger")

            <input type="submit" name="save" value="Kaydet" />
        }
    </fieldset>
    <fieldset>
        <legend>Style uygulayarak:</legend>
        @Html.Label("txt","Adress:")
        @Html.TextArea("txt",new {@style="border:2px solid black; background:red;" })
    </fieldset>
</body>
</html>

HtmlHelpers/Views/StandardHtmlHelpers/TextBox.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>TextBox</title>
    <style>
        .txt
        {
            border:1px solid #ccc;
            padding: 2px;
            font-size:1.2em;
            color :red;
            width:200px;
            background:#000000;
        }
    </style>
</head>
<body>
    <div> 
        <fieldset>
            <legend>
                Html form post ile 
            </legend>
            <form action="" method="post">
                Adi : <input type="text" name="adi" /><br />
                Soyadi : <input type="text" name="adi" />
                <input type="submit" value="Kaydet"/>
            </form>
        </fieldset>
    </div>
    <div>
        <fieldset>
            <legend>
                Html.TextBox Kullanimi
                 @*Html deki <input type şeklindeki elementleri
                     Standard Html helper Metodu olan Html.TextBox
                     ile yapabiliriz.*@
            </legend>
           @using (Html.BeginForm())
           {
              <label> Adi: @Html.TextBox("adi","Mustafa",new { @disabled ="disabled"}) </label>
            <label> Soyadi: @Html.TextBox("adi","Ekici",new { @readonly=true }) </label>
            <input type="submit" value="Kaydet" />
           }
        </fieldset>
    </div>
    <fieldset>
        <legend>
            Style uygulayarak
        </legend>
        @using (Html.BeginForm())
        {
            <label> Adi: @Html.TextBox("adi", "Mustafa",new {@class="txt" })</label>  
            <label> Soyadi: @Html.TextBox("adi") </label>
            <input type="submit" value="Kaydet" />
        }
    </fieldset>

</body>
</html>